<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <RootNamespace>GenderedMoralGuideTitles</RootNamespace>
    <AssemblyName>GenderedMoralGuideTitles</AssemblyName>
    <Nullable>enable</Nullable>
    <UnityModules>CoreModule;IMGUIModule;TextRenderingModule</UnityModules>
  </PropertyGroup></Project>

